# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editUnitWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editUnitWindow(object):
    def setupUi(self, editUnitWindow):
        editUnitWindow.setObjectName("editUnitWindow")
        editUnitWindow.resize(552, 514)
        self.buttonBox = QtWidgets.QDialogButtonBox(editUnitWindow)
        self.buttonBox.setGeometry(QtCore.QRect(200, 480, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(editUnitWindow)
        self.frame.setGeometry(QtCore.QRect(0, 0, 541, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 541, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.generalTab = QtWidgets.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.tabWidget.addTab(self.generalTab, "")
        self.sectionTab = QtWidgets.QWidget()
        self.sectionTab.setObjectName("sectionTab")
        self.frame_2 = QtWidgets.QFrame(self.sectionTab)
        self.frame_2.setGeometry(QtCore.QRect(0, 410, 531, 31))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.exportButton = QtWidgets.QPushButton(self.frame_2)
        self.exportButton.setGeometry(QtCore.QRect(250, 10, 56, 17))
        self.exportButton.setObjectName("exportButton")
        self.importButton = QtWidgets.QPushButton(self.frame_2)
        self.importButton.setGeometry(QtCore.QRect(190, 10, 56, 17))
        self.importButton.setObjectName("importButton")
        self.deleteButton = QtWidgets.QPushButton(self.frame_2)
        self.deleteButton.setGeometry(QtCore.QRect(130, 10, 56, 17))
        self.deleteButton.setObjectName("deleteButton")
        self.modifyButton = QtWidgets.QPushButton(self.frame_2)
        self.modifyButton.setGeometry(QtCore.QRect(70, 10, 56, 17))
        self.modifyButton.setObjectName("modifyButton")
        self.newButton = QtWidgets.QPushButton(self.frame_2)
        self.newButton.setGeometry(QtCore.QRect(10, 10, 56, 17))
        self.newButton.setObjectName("newButton")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.sectionTab)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, 20, 271, 391))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 269, 389))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.treeView_2 = QtWidgets.QTreeView(self.scrollAreaWidgetContents_3)
        self.treeView_2.setGeometry(QtCore.QRect(0, 0, 256, 391))
        self.treeView_2.setObjectName("treeView_2")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.frame_3 = QtWidgets.QFrame(self.sectionTab)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 531, 21))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.bothEndsCheckBox_2 = QtWidgets.QCheckBox(self.frame_3)
        self.bothEndsCheckBox_2.setGeometry(QtCore.QRect(20, 0, 101, 20))
        self.bothEndsCheckBox_2.setObjectName("bothEndsCheckBox_2")
        self.endButton = QtWidgets.QPushButton(self.frame_3)
        self.endButton.setGeometry(QtCore.QRect(470, 0, 56, 17))
        self.endButton.setObjectName("endButton")
        self.startButton = QtWidgets.QPushButton(self.frame_3)
        self.startButton.setGeometry(QtCore.QRect(410, 0, 56, 17))
        self.startButton.setObjectName("startButton")
        self.frame_4 = QtWidgets.QFrame(self.sectionTab)
        self.frame_4.setGeometry(QtCore.QRect(279, 20, 251, 391))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.frame_4)
        self.openGLWidget.setGeometry(QtCore.QRect(0, 0, 251, 200))
        self.openGLWidget.setObjectName("openGLWidget")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.frame_4)
        self.scrollArea_4.setGeometry(QtCore.QRect(0, 200, 251, 191))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 249, 189))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.listView = QtWidgets.QListView(self.scrollAreaWidgetContents_4)
        self.listView.setGeometry(QtCore.QRect(0, 0, 231, 192))
        self.listView.setObjectName("listView")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.tabWidget.addTab(self.sectionTab, "")
        self.endConditionsTab = QtWidgets.QWidget()
        self.endConditionsTab.setObjectName("endConditionsTab")
        self.openGLWidget_2 = QtWidgets.QOpenGLWidget(self.endConditionsTab)
        self.openGLWidget_2.setGeometry(QtCore.QRect(310, 189, 221, 261))
        self.openGLWidget_2.setObjectName("openGLWidget_2")
        self.frame_5 = QtWidgets.QFrame(self.endConditionsTab)
        self.frame_5.setGeometry(QtCore.QRect(0, 150, 531, 31))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.bothEndsCheckBox = QtWidgets.QCheckBox(self.frame_5)
        self.bothEndsCheckBox.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.bothEndsCheckBox.setObjectName("bothEndsCheckBox")
        self.startButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.startButton_2.setGeometry(QtCore.QRect(410, 10, 56, 17))
        self.startButton_2.setObjectName("startButton_2")
        self.endButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.endButton_2.setGeometry(QtCore.QRect(470, 10, 56, 17))
        self.endButton_2.setObjectName("endButton_2")
        self.frame_6 = QtWidgets.QFrame(self.endConditionsTab)
        self.frame_6.setGeometry(QtCore.QRect(0, 180, 181, 261))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.exCheckBox = QtWidgets.QCheckBox(self.frame_6)
        self.exCheckBox.setGeometry(QtCore.QRect(10, 40, 111, 16))
        self.exCheckBox.setObjectName("exCheckBox")
        self.eyCheckBox = QtWidgets.QCheckBox(self.frame_6)
        self.eyCheckBox.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.eyCheckBox.setObjectName("eyCheckBox")
        self.ezCheckBox = QtWidgets.QCheckBox(self.frame_6)
        self.ezCheckBox.setGeometry(QtCore.QRect(10, 80, 111, 16))
        self.ezCheckBox.setObjectName("ezCheckBox")
        self.phixCheckBox = QtWidgets.QCheckBox(self.frame_6)
        self.phixCheckBox.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.phixCheckBox.setObjectName("phixCheckBox")
        self.phiyCheckBox = QtWidgets.QCheckBox(self.frame_6)
        self.phiyCheckBox.setGeometry(QtCore.QRect(10, 120, 111, 16))
        self.phiyCheckBox.setObjectName("phiyCheckBox")
        self.phizCheckBox = QtWidgets.QCheckBox(self.frame_6)
        self.phizCheckBox.setGeometry(QtCore.QRect(10, 140, 111, 16))
        self.phizCheckBox.setObjectName("phizCheckBox")
        self.fixedButton = QtWidgets.QPushButton(self.frame_6)
        self.fixedButton.setGeometry(QtCore.QRect(10, 220, 31, 31))
        self.fixedButton.setObjectName("fixedButton")
        self.pinnedButton = QtWidgets.QPushButton(self.frame_6)
        self.pinnedButton.setGeometry(QtCore.QRect(50, 220, 31, 31))
        self.pinnedButton.setObjectName("pinnedButton")
        self.releasesLabel = QtWidgets.QLabel(self.frame_6)
        self.releasesLabel.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.releasesLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.releasesLabel.setObjectName("releasesLabel")
        self.exLineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.exLineEdit.setGeometry(QtCore.QRect(120, 40, 51, 16))
        self.exLineEdit.setObjectName("exLineEdit")
        self.eyLineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.eyLineEdit.setGeometry(QtCore.QRect(120, 60, 51, 16))
        self.eyLineEdit.setObjectName("eyLineEdit")
        self.ezLineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.ezLineEdit.setGeometry(QtCore.QRect(120, 80, 51, 16))
        self.ezLineEdit.setObjectName("ezLineEdit")
        self.phixLineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.phixLineEdit.setGeometry(QtCore.QRect(120, 100, 51, 16))
        self.phixLineEdit.setObjectName("phixLineEdit")
        self.phiyLineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.phiyLineEdit.setGeometry(QtCore.QRect(120, 120, 51, 16))
        self.phiyLineEdit.setObjectName("phiyLineEdit")
        self.phizLineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.phizLineEdit.setGeometry(QtCore.QRect(120, 140, 51, 16))
        self.phizLineEdit.setObjectName("phizLineEdit")
        self.frame_7 = QtWidgets.QFrame(self.endConditionsTab)
        self.frame_7.setGeometry(QtCore.QRect(200, 190, 101, 261))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.eccentricityLabel = QtWidgets.QLabel(self.frame_7)
        self.eccentricityLabel.setGeometry(QtCore.QRect(0, 0, 101, 16))
        self.eccentricityLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.eccentricityLabel.setObjectName("eccentricityLabel")
        self.yLabel = QtWidgets.QLabel(self.frame_7)
        self.yLabel.setGeometry(QtCore.QRect(10, 30, 21, 16))
        self.yLabel.setObjectName("yLabel")
        self.zLabel = QtWidgets.QLabel(self.frame_7)
        self.zLabel.setGeometry(QtCore.QRect(10, 50, 21, 16))
        self.zLabel.setObjectName("zLabel")
        self.yLineEdit = QtWidgets.QLineEdit(self.frame_7)
        self.yLineEdit.setGeometry(QtCore.QRect(40, 30, 51, 16))
        self.yLineEdit.setObjectName("yLineEdit")
        self.zLineEdit = QtWidgets.QLineEdit(self.frame_7)
        self.zLineEdit.setGeometry(QtCore.QRect(40, 50, 51, 16))
        self.zLineEdit.setObjectName("zLineEdit")
        self.frame_8 = QtWidgets.QFrame(self.endConditionsTab)
        self.frame_8.setGeometry(QtCore.QRect(10, 10, 521, 131))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.eccLabel = QtWidgets.QLabel(self.frame_8)
        self.eccLabel.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.eccLabel.setObjectName("eccLabel")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 10, 56, 17))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 10, 56, 17))
        self.pushButton_6.setObjectName("pushButton_6")
        self.considerEccCheckBox = QtWidgets.QCheckBox(self.frame_8)
        self.considerEccCheckBox.setGeometry(QtCore.QRect(10, 40, 271, 16))
        self.considerEccCheckBox.setObjectName("considerEccCheckBox")
        self.tabWidget.addTab(self.endConditionsTab, "")
        self.materialTab = QtWidgets.QWidget()
        self.materialTab.setObjectName("materialTab")
        self.scrollArea = QtWidgets.QScrollArea(self.materialTab)
        self.scrollArea.setGeometry(QtCore.QRect(270, 0, 251, 381))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 249, 379))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tableView = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 251, 381))
        self.tableView.setObjectName("tableView")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.materialTab)
        self.scrollArea_2.setGeometry(QtCore.QRect(-1, -1, 271, 381))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 269, 379))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.treeView = QtWidgets.QTreeView(self.scrollAreaWidgetContents_2)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 256, 381))
        self.treeView.setObjectName("treeView")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.frame_9 = QtWidgets.QFrame(self.materialTab)
        self.frame_9.setGeometry(QtCore.QRect(0, 410, 531, 31))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.exportButton_2 = QtWidgets.QPushButton(self.frame_9)
        self.exportButton_2.setGeometry(QtCore.QRect(250, 10, 56, 17))
        self.exportButton_2.setObjectName("exportButton_2")
        self.importButton_2 = QtWidgets.QPushButton(self.frame_9)
        self.importButton_2.setGeometry(QtCore.QRect(190, 10, 56, 17))
        self.importButton_2.setObjectName("importButton_2")
        self.deleteButton_2 = QtWidgets.QPushButton(self.frame_9)
        self.deleteButton_2.setGeometry(QtCore.QRect(130, 10, 56, 17))
        self.deleteButton_2.setObjectName("deleteButton_2")
        self.modifyButton_2 = QtWidgets.QPushButton(self.frame_9)
        self.modifyButton_2.setGeometry(QtCore.QRect(70, 10, 56, 17))
        self.modifyButton_2.setObjectName("modifyButton_2")
        self.newButton_2 = QtWidgets.QPushButton(self.frame_9)
        self.newButton_2.setGeometry(QtCore.QRect(10, 10, 56, 17))
        self.newButton_2.setObjectName("newButton_2")
        self.tabWidget.addTab(self.materialTab, "")

        self.retranslateUi(editUnitWindow)
        self.tabWidget.setCurrentIndex(2)
        self.buttonBox.accepted.connect(editUnitWindow.accept)
        self.buttonBox.rejected.connect(editUnitWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(editUnitWindow)

    def retranslateUi(self, editUnitWindow):
        _translate = QtCore.QCoreApplication.translate
        editUnitWindow.setWindowTitle(_translate("editUnitWindow", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generalTab), _translate("editUnitWindow", "General"))
        self.exportButton.setText(_translate("editUnitWindow", "Export"))
        self.importButton.setText(_translate("editUnitWindow", "Import"))
        self.deleteButton.setText(_translate("editUnitWindow", "Delete"))
        self.modifyButton.setText(_translate("editUnitWindow", "Modify"))
        self.newButton.setText(_translate("editUnitWindow", "New"))
        self.bothEndsCheckBox_2.setText(_translate("editUnitWindow", "Same at both ends"))
        self.endButton.setText(_translate("editUnitWindow", "End"))
        self.startButton.setText(_translate("editUnitWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sectionTab), _translate("editUnitWindow", "Section"))
        self.bothEndsCheckBox.setText(_translate("editUnitWindow", "The same at both ends"))
        self.startButton_2.setText(_translate("editUnitWindow", "Start"))
        self.endButton_2.setText(_translate("editUnitWindow", "End"))
        self.exCheckBox.setText(_translate("editUnitWindow", "e,x\'..............................."))
        self.eyCheckBox.setText(_translate("editUnitWindow", "e,y\'..............................."))
        self.ezCheckBox.setText(_translate("editUnitWindow", "e,z\'..............................."))
        self.phixCheckBox.setText(_translate("editUnitWindow", "phi,x\'............................"))
        self.phiyCheckBox.setText(_translate("editUnitWindow", "phi,y\'............................"))
        self.phizCheckBox.setText(_translate("editUnitWindow", "phi,z\'............................"))
        self.fixedButton.setText(_translate("editUnitWindow", "fixed"))
        self.pinnedButton.setText(_translate("editUnitWindow", "pinned"))
        self.releasesLabel.setText(_translate("editUnitWindow", "Releases [kN/m, kNm/degree"))
        self.eccentricityLabel.setText(_translate("editUnitWindow", "Eccentricity [m]"))
        self.yLabel.setText(_translate("editUnitWindow", "y\'......"))
        self.zLabel.setText(_translate("editUnitWindow", "z\'......"))
        self.eccLabel.setText(_translate("editUnitWindow", "Eccentricity in analytical model ............."))
        self.pushButton_5.setText(_translate("editUnitWindow", "PushButton"))
        self.pushButton_6.setText(_translate("editUnitWindow", "PushButton"))
        self.considerEccCheckBox.setText(_translate("editUnitWindow", "Consider eccentricity caused by cracking in cracked section analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.endConditionsTab), _translate("editUnitWindow", "End Conditions"))
        self.exportButton_2.setText(_translate("editUnitWindow", "Export"))
        self.importButton_2.setText(_translate("editUnitWindow", "Import"))
        self.deleteButton_2.setText(_translate("editUnitWindow", "Delete"))
        self.modifyButton_2.setText(_translate("editUnitWindow", "Modify"))
        self.newButton_2.setText(_translate("editUnitWindow", "New"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.materialTab), _translate("editUnitWindow", "Material"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editUnitWindow = QtWidgets.QDialog()
    ui = Ui_editUnitWindow()
    ui.setupUi(editUnitWindow)
    editUnitWindow.show()
    sys.exit(app.exec_())

