# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1196, 869)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rightFrame = QtWidgets.QFrame(self.centralwidget)
        self.rightFrame.setGeometry(QtCore.QRect(1090, 80, 31, 581))
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.pushButton_27 = QtWidgets.QPushButton(self.rightFrame)
        self.pushButton_27.setGeometry(QtCore.QRect(0, 60, 31, 31))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_26 = QtWidgets.QPushButton(self.rightFrame)
        self.pushButton_26.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_25 = QtWidgets.QPushButton(self.rightFrame)
        self.pushButton_25.setGeometry(QtCore.QRect(0, 30, 31, 31))
        self.pushButton_25.setObjectName("pushButton_25")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(30, 80, 1061, 581))
        self.openGLWidget.setObjectName("openGLWidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 1121, 81))
        self.tabs.setObjectName("tabs")
        self.structureTab = QtWidgets.QWidget()
        self.structureTab.setObjectName("structureTab")
        self.structureFrame = QtWidgets.QFrame(self.structureTab)
        self.structureFrame.setGeometry(QtCore.QRect(0, 0, 491, 61))
        self.structureFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.structureFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.structureFrame.setObjectName("structureFrame")
        self.columnButton = QtWidgets.QPushButton(self.structureFrame)
        self.columnButton.setGeometry(QtCore.QRect(0, 0, 61, 61))
        self.columnButton.setObjectName("columnButton")
        self.beamButton = QtWidgets.QPushButton(self.structureFrame)
        self.beamButton.setGeometry(QtCore.QRect(60, 0, 61, 61))
        self.beamButton.setObjectName("beamButton")
        self.tabs.addTab(self.structureTab, "")
        self.loadsTab = QtWidgets.QWidget()
        self.loadsTab.setObjectName("loadsTab")
        self.structureFrame_2 = QtWidgets.QFrame(self.loadsTab)
        self.structureFrame_2.setGeometry(QtCore.QRect(0, 0, 491, 61))
        self.structureFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.structureFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.structureFrame_2.setObjectName("structureFrame_2")
        self.loadCaseButton = QtWidgets.QPushButton(self.structureFrame_2)
        self.loadCaseButton.setGeometry(QtCore.QRect(0, 0, 61, 61))
        self.loadCaseButton.setObjectName("loadCaseButton")
        self.loadGroupsButton = QtWidgets.QPushButton(self.structureFrame_2)
        self.loadGroupsButton.setGeometry(QtCore.QRect(60, 0, 61, 61))
        self.loadGroupsButton.setObjectName("loadGroupsButton")
        self.loadCombinationButton = QtWidgets.QPushButton(self.structureFrame_2)
        self.loadCombinationButton.setGeometry(QtCore.QRect(120, 0, 61, 61))
        self.loadCombinationButton.setObjectName("loadCombinationButton")
        self.tabs.addTab(self.loadsTab, "")
        self.leftFrame = QtWidgets.QFrame(self.centralwidget)
        self.leftFrame.setGeometry(QtCore.QRect(0, 80, 31, 581))
        self.leftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.pushButton_22 = QtWidgets.QPushButton(self.leftFrame)
        self.pushButton_22.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.leftFrame)
        self.pushButton_23.setGeometry(QtCore.QRect(0, 30, 31, 31))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.leftFrame)
        self.pushButton_24.setGeometry(QtCore.QRect(0, 60, 31, 31))
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 700, 81, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 660, 1121, 31))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 0, 30, 30))
        self.pushButton_14.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_14.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame)
        self.pushButton_13.setGeometry(QtCore.QRect(30, 0, 30, 30))
        self.pushButton_13.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_13.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame)
        self.pushButton_15.setGeometry(QtCore.QRect(1090, 0, 30, 30))
        self.pushButton_15.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_15.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame)
        self.pushButton_16.setGeometry(QtCore.QRect(1060, 0, 30, 30))
        self.pushButton_16.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_16.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_16.setObjectName("pushButton_16")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1196, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuWindwos = QtWidgets.QMenu(self.menubar)
        self.menuWindwos.setObjectName("menuWindwos")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindwos.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_27.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_26.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_25.setText(_translate("MainWindow", "PushButton"))
        self.columnButton.setText(_translate("MainWindow", "Column"))
        self.beamButton.setText(_translate("MainWindow", "Beam"))
        self.tabs.setTabText(self.tabs.indexOf(self.structureTab), _translate("MainWindow", "Structure"))
        self.loadCaseButton.setText(_translate("MainWindow", "Load Cases"))
        self.loadGroupsButton.setText(_translate("MainWindow", "Load Groups"))
        self.loadCombinationButton.setText(_translate("MainWindow", "Load Combinations"))
        self.tabs.setTabText(self.tabs.indexOf(self.loadsTab), _translate("MainWindow", "Loads"))
        self.pushButton_22.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_23.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_24.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_13.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_15.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_16.setText(_translate("MainWindow", "PushButton"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuWindwos.setTitle(_translate("MainWindow", "Windows"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save As..."))
        self.actionPrint.setText(_translate("MainWindow", "Print"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

